# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:53
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20171102_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='section',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'log_section_autocomplete', help_text=b'Please choose relevant sections', initial='Documentation/Report, Meeting/Communication, Project/Coding', space_delimiter=False, to='logbook.Section'),
        ),
    ]
