# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 01:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_auto_20171102_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='label',
            field=models.CharField(default=datetime.datetime(2017, 11, 2, 1, 21, 59, 878376, tzinfo=utc), help_text='The name of the tag, without ancestors', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='level',
            field=models.IntegerField(default=1, help_text='The level of the tag in the tree'),
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='logbook.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='path',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='section',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'log_section_autocomplete', help_text=b'Please choose relevant sections', initial='Documentation/Report, Meeting/Communication, Project/Coding', space_delimiter=False, to='logbook.Section', tree=True),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('slug', 'parent')]),
        ),
    ]
